name: button-group
label: Button group
status: wip
context:
  item: [true, true, true]
variants:
  - name: primary-outline
    context:
      item:
        - button:
            modifier: [primary-outline]
        - button:
            modifier: [primary-outline]
            isActive: true
        - button:
            modifier: [primary-outline]