name: button-group
label: Button group
status: wip
context:
  button: [true, true, true]
  modifier: null
variants:
  - name: primary-outline
    context:
      button:
        - modifier: [primary-outline]
        - modifier: [primary-outline]
          state:
            isActive: true
        - modifier: [primary-outline]
  - name: flex
    context:
      button:
        - true
        - state:
            isActive: true
        - true
      modifier: [flex]
