name: pagination
label: Pagination
status: wip
context:
  item:
    - icon:
        source: chevron-left
      disabled: true
    - number: 1
    - number: 2
      isActive: true
    - number: 3
    - number: 4
    - number: 5
    - icon:
        source: chevron-right
