name: pagination
label: Pagination
status: wip
context:
  item:
    - element:
        icon:
          property:
            icon: chevron-left
      state:
        disabled: true
    - property:
        number: 1
    - property:
        number: 2
      state:
        isActive: true
    - property:
        number: 3
    - property:
        number: 4
    - property:
        number: 5
    - element:
        icon:
          property:
            icon: chevron-right
