name: tab
label: Tab
status: wip
context:
  item:
    - property:
        text: First
        url: '#'
    - property:
        text: First
        url: '#'
      state:
        isActive: true
    - property:
        text: First
        url: '#'
