name: search
label: Search
status: review
context:
  icon:
    source: search
  field:
    type: search
    formControl: true
    placeholder: Search
    class: [search_input]
  modifier: null
variants:
  - name: dark
    context:
      modifier: [dark]
  - name: light
    preview: '@jha-content--dark'
    context:
      modifier: [light]
