name: search
label: Search
status: wip
context:
  icon:
    source: search
  modifier: null
variants:
  - name: dark
    context:
      modifier: [dark]
  - name: light
    context:
      modifier: [light]
