name: search
label: Search
status: wip
context:
  element:
    icon:
      property:
        icon: search
  modifier: null
variants:
  - name: dark
    context:
      modifier: [dark]
  - name: light
    context:
      modifier: [light]
