name: progress
label: Progress
status: wip
context:
  isCircular: true
  value: null
  helper: null
  modifier: null
variants:
  - name: circular-inline
    label: Circular, Inline
    context:
      isCircular: true
      modifier: [inline]
  - name: circular-center
    label: Circular, Center
    context:
      isCircular: true
      modifier: [center]
  - name: circular-small
    label: Circular, Small
    context:
      isCircular: true
      modifier: [sm]
  - name: linear
    context:
      isCircular: false
      value: 60
  - name: linear-helper
    context:
      isCircular: false
      value: 60
      helper: true
  - name: ie9
    context:
      value: 60
