name: button
label: Buttons
status: wip
context:
  property:
    link: null
    icon: null
    text: Lorem ipsum
  modifier: [default]
  state:
    isActive: false
variants:
  - name: block
    label: Block
    context:
      modifier: [primary, block]
  - name: link
    label: Link
    context:
      property:
        link:
        url: '#'
      modifier: [link]
  - name: toggle
    label: Toggle
    context:
      modifier: [toggle]
  - name: icon
    label: Icon
    context:
      button:
        - property:
            icon:
              icon: apple
          modifier: [default, icon]
        - property:
            icon:
              icon: apple
          modifier: [link, icon]
        - property:
            icon:
              icon: apple
          modifier: [primary, icon]
  - name: fill
    label: Fill
    context:
      button:
        - modifier: [neutral]
        - modifier: [primary]
        - modifier: [success]
        - modifier: [danger]
      state:
        - modifier: [default]
        - modifier: [default]
        - modifier: [default]

  - name: outline
    label: Outline
    context:
      button:
        - modifier: [default]
        - modifier: [primary-outline]
        - modifier: [success-outline]
        - modifier: [danger-outline]
  - name: size
    context:
      button:
        - modifier: [default, sm]
        - modifier: [default]
        - modifier: [default, lg]
        - modifier: [default, wide]
  - name: align
    label: Alignment
    context:
      button:
        - align: left
          modifier: [primary, align-left]
        - align: right
          modifier: [primary, align-right]