name: card
label: Card
status: wip
context:
  modifier: null
  header:
    title: Sample title
    subTitle: Sample subtitle
    modifier: null
  action: null
  media: null
  content:
    modifier: null
    #empty:
    #  text: There are no scheduled messages.
    #loading: true
    error:
      loadingImg: ":'("
      text: Failed to get money movement stats.
      retry:
        text: Try again
        url: '#'
    container: Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam voluptates ex dolores praesentium fuga odio quis cumque laudantium, soluta reiciendis facere perferendis aut dolor alias, est dolore minima. Molestiae, voluptatem?
    footer: null
variants:
  - name: loading
    context:
      content:
        loading: true
  - name: wide
    context:
      modifier: [wide]
  - name: reset
    context:
      modifier: [reset]
  - name: summary
    context:
      modifier: [summary]
  - name: footer
    context:
      footer:
        text: More
        url: '#'
  - name: media
    context:
      media:
        src: http://unsplash.it/1920/1080?random
  - name: summary-media
    context:
      modifier: [summary]
      media:
        src: http://unsplash.it/1920/1080?random
  - name: content
  - name: error
    context:
      header:
        title: Lorem ipsum dolor
        subTitle: Lorem ipsum dolor sit amet
      error:
        loadingImg: ":'("
        text: Failed to get money movement stats.
        retry:
          text: Try later
          url: '#'
