name: avatar
label: Avatar
status: review
context:
  img:
    src: https://i.pravatar.cc/300
    alt: Anon Anonymous
  isBgImg: false
  modifier: null
  tooltip: false
  badge: false
variants:
  - name: xs
    label: Extra small
    context:
      modifier: [xs]
  - name: sm
    label: Small
    context:
      modifier: [sm]
  - name: md
    label: Medium
    context:
      modifier: [md]
  - name: lg
    label: Large
    context:
      modifier: [lg]
  - name: xl
    label: Extra large
    context:
      modifier: [xl]
  - name: left
    label: Align left
    context:
      modifier: [left]
  - name: right
    label: Align right
    context:
      modifier: [right]
  - name: you
    label: You
    context:
      modifier: [you]
  - name: badge
    label: Badge
    context:
      badge:
        img:
          src: https://i.pravatar.cc/300
          alt: Badge image
  - name: background-image
    context:
      isBgImg: true
  - name: tooltip
    context:
      tooltip:
        modifier: [e]
