name: sample
status: wip
preview: null
context:
  theme:
    color: '#8d99a0'
  apps:
    modifier: [link, icon]
    utility: [visible@mobile]
    icon:
      source: apps
    link:
      url: '#'
  rightNow:
    modifier: [wide]
    header:
      title: Right now
      subTitle: Last 5 minutes
    loggedInUsers:
      modifier: [center]
      icon:
        source: person
        utility: [fill-neutral]
      subtitle: Logged in users
      value: 5
    signUps:
      modifier: [center]
      icon:
        source: person-add
        utility: [fill-neutral]
      subtitle: Sign ups today
      value: 0
    userLogins:
      modifier: [center]
      icon:
        source: today
        utility: [fill-neutral]
      subtitle: User logins today
      value: 322
    averageSession:
      modifier: [center]
      icon:
        source: schedule
        utility: [fill-neutral]
      subtitle: Average session
      value: 2m
  userLookup:
    modifier: [wide]
    header:
      title: User lookup
  moneyMovement:
    modifier: [wide]
    header:
      title: Money movement
      subTitle: Last 30 days
    content:
      error:
        loadingImg: ":'("
        text: Failed to get money movement stats.
        retry:
          url: '#'
          text: Try again
    footer:
      button:
        text: More
        modifier: [toggle, align-left]
  usage:
    modifier: [wide]
    header:
      title: Usage
      subTitle: Last 30 days
    activeUsers:
      value: 638
      comparison:
        value: 671
        icon:
          modifier: [sm]
          source: arrow-drop-up
          utility: [fill-success]
    retention:
      value: 93.3%
      comparison:
        value: 93.1%
        icon:
          modifier: [sm]
          source: arrow-drop-up
          utility: [fill-success]
    signUps:
      value: 24
      comparison:
        value: 27
        icon:
          modifier: [sm]
          source: arrow-drop-down
          utility: [fill-danger]
    platformUsage:
      modifier: [borderless]
      item:
        - modifier: [inset]
          icon:
            source: android
            utility: [fill-neutral]
          progress:
            type: linear
            value: 64
            helper: true
        - modifier: [inset]
          icon:
            source: apple
            utility: [fill-neutral]
          progress:
            type: linear
            value: 33
            helper: true
        - modifier: [inset]
          icon:
            source: windows
            utility: [fill-neutral]
          progress:
            type: linear
            value: 2
            helper: true
    footer:
      button:
        text: More
        modifier: [toggle, align-left]
  rdcRequests:
    modifier: [wide]
    header:
      title: RDC requests
    content:
      modifier: [no-spacing]
    list:
      item:
        - avatar:
            img:
              src: http://unsplash.it/900/900?random=1
          title: Chris Austin
          subTitle: Individual
          time: 2h ago
          modifier: [inset, hover]
        - avatar:
            img:
              src: http://unsplash.it/900/900?random=2
          title: Anon Anonymous
          subTitle: Individual
          time: 3h ago
          modifier: [inset, hover]
  lockedOutUsers:
    modifier: [wide]
    header:
      title: Locked-out users
    content:
      empty:
        text: There are no locked-out users.
  releaseNotes:
    modifier: [wide]
    header:
      title: Release notes
    content:
      loading: true
  messages:
    modifier: [wide]
    media:
      src: http://unsplash.it/1920/1080?random
    header:
      title: Messages
    content:
      empty:
        text: There are no scheduled messages.
    footer:
      button:
        text: More
        modifier: [toggle, align-left]
  sampleGrid:
    item:
      - breakpoint:
          col: 6
          viewport: xs
        

variants:
  - name: blue
    context:
      theme:
        color: '#3aaeda'
  - name: green
    context:
      theme:
        color: '#4caf50'
  - name: yellow
    context:
      theme:
        color: '#fca902'
  - name: red
    context:
      theme:
        color: '#f44336'
  - name: purple
    context:
      theme:
        color: '#7d57c1'
