name: thumbnail
label: Thumbnail
status: review
context:
  url: http://unsplash.it/900/900?random
  alt: Alternative text
  isBackground: false
  modifier: null
variants:
  - name: xs
    label: Extra Small
    context:
      modifier: [xs]
  - name: sm
    label: Small
    context:
      modifier: [sm]
  - name: md
    label: Medium
    context:
      modifier: [md]
  - name: lg
    label: Large
    context:
      modifier: [lg]
  - name: xl
    label: Extra Large
    context:
      modifier: [xl]
  - name: bg-img
    label: Background Image
    context:
      bgImg: true
