name: thumbnail
label: Thumbnail
status: wip
context:
  property:
    url: http://unsplash.it/900/900?random
    alt: Alternative text
  modifier: null
  type:
    bgImg: false
variants:
  - name: xs
    context:
      modifier: [xs]
  - name: sm
    context:
      modifier: [sm]
  - name: md
    context:
      modifier: [md]
  - name: lg
    context:
      modifier: [lg]
  - name: xl
    context:
      modifier: [xl]
  - name: inline
    context:
      type:
        bgImg: true
