name: gallery
label: Gallery
status: review
context:
  image: true
  item:
    - url: http://unsplash.it/1920/1080?random=1
      grid:
        - col: 4
          breakpoint: xs
    - url: http://unsplash.it/1920/1080?random=2
      grid:
        - col: 4
          breakpoint: xs
    - url: http://unsplash.it/1920/1080?random=3
      grid:
        - col: 4
          breakpoint: xs
    - url: http://unsplash.it/1920/1080?random=4
      grid:
        - col: 4
          breakpoint: xs
      isSelected: true
      title: Lorem ipsum dolor sit amet consectetur
      size: 252.6kb
      icon:
        source: check
    - url: http://unsplash.it/1920/1080?random=5
      grid:
        - col: 4
          breakpoint: xs
    - url: http://unsplash.it/1920/1080?random=6
      grid:
        - col: 4
          breakpoint: xs
    - url: http://unsplash.it/1920/1080?random=7
      grid:
        - col: 4
          breakpoint: xs
    - url: http://unsplash.it/1920/1080?random=8
      grid:
        - col: 4
          breakpoint: xs
    - url: http://unsplash.it/1920/1080?random=9
      grid:
        - col: 4
          breakpoint: xs
