name: timeline
label: Timeline
status: wip
context:
  item:
    - property:
        date: Today
      element:
        activity:
          - time: 2:01 pm
            description: Lorem ipsum dolor sit amet consectetur.
            action:
              text: View
              url: '#'
          - time: 1:32 pm
            description: created a new untitled ad.
    - property:
        date: Yesterday
      element:
        activity:
          - time: 8:36 am
            description: Some additional information
            action:
              text: View
              url: '#'
variants:
  - name: type
    label: Type
    context:
      item:
        - date: Today
          activity:
            - type:
                icon:
                  property:
                    icon: message
              time: 2:01 pm
              description: Lorem ipsum dolor sit amet consectetur.
              action:
                text: View
                url: '#'
            - type:
                icon:
                  property:
                    icon: message
              time: 1:32 pm
              description: created a new untitled ad.
        - date: Yesterday
          activity:
            - type:
                icon:
                  property:
                    icon: person
              time: 8:36 am
              description: Some additional information
              action:
                text: View
                url: '#'
