name: dialog
label: Dialog
status: wip
context:
  modifier: [center@xs]
  isVisible: true
  backdrop:
    modifier: [fill]
    isVisible: true
  inner:
    modifier: [sm]
  header:
    modifier: null
    text: Lorem ipsum dolor
  button:
    property:
      icon: close
    modifier: [icon]
  content:
    modifier: null
    slot: Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur dolore neque quia laboriosam voluptatibus, impedit accusantium exercitationem earum hic, aliquid rem excepturi suscipit praesentium dolor. In maiores delectus esse quo.
  footer:
    slot: Lorem ipsum dolor sit amet consectetur.
variants:
  - name: wide
    label: Wide
    context:
      inner:
        modifier: [lg]
  - name: profile
    label: Profile
    context:
      header:
        modifier: [profile]
      footer: false
  - name: gallery
    label: Gallery content
    context:
      content:
        gallery:
          item:
            - url: http://unsplash.it/1920/1080?random=1
            - url: http://unsplash.it/1920/1080?random=2
      footer: false
  - name: footer
    label: Footer
    context:
      footer:
        button:
          - modifier: [success]
            text: Okay
          - modifier: [danger]
            text: Nevermind
