name: message
label: Message
status: review
context:
  modifier: null
  isFluid: true
  date: Jan. 28, 2020
  heading:
    avatar: null
    title: Lorem ipsum dolor sit amet consectetur
  content: Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur quibusdam ducimus sunt!
variants:
  - name: note
    label: Note
    context:
      modifier: [note]
  - name: avatar
    label: Avatar
    context:
      modifier: [note]
      heading:
        avatar: true
  - name: non-fluid
    label: Non-fluid Container
    context:
      isFluid: false
  - name: conversation
    label: Conversation
    context:
      message:
        - heading:
            avatar: true
            title: Anon Anonymous
        - heading:
            avatar: true
            title: Anon Anonymous
        - heading:
            avatar: true
            title: Anon Anonymous
