name: icon
label: Icon
status: wip
context:
  isPresentation: false
  source: apple
  title: Lorem ipsum
  modifier: null
  utility: null
variants:
  - name: presentation
    label: Presentation
    context:
      isPresentation: true
  - name: xs
    label: Size, Extra Small
    context:
      modifier: [xs]
  - name: sm
    label: Size, Small
    context:
      modifier: [sm]
  - name: lg
    label: Size, Large
    context:
      modifier: [lg]
  - name: xl
    label: Size, Extra Large
    context:
      modifier: [xl]
  - name: primary
    label: Color, Primary
    context:
      utility: [fill-primary]
  - name: success
    label: Color, Success
    context:
      utility: [fill-success]
  - name: Danger
    label: Color, Danger
    context:
      utility: [fill-danger]
  - name: Base
    label: Color, Base
    context:
      utility: [fill-base]
  - name: Light
    label: Color, Light
    context:
      utility: [fill-light]
  - name: Muted
    label: Color, Muted
    context:
      utility: [fill-muted]
  - name: Neutral
    label: Color, Neutral
    context:
      utility: [fill-neutral]
