name: toast
label: Toast
status: review
context:
  toastSlot: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus cum ex labore!
  isVisible: true
  modifier: null
variants:
  - name: danger
    label: Danger
    context:
      modifier: [danger]
  - name: content
    label: Sample Content
    context:
      modifier: [danger]
      icon:
        source: battery-alert
        utility: [float-left]
      content:
        heading: false
        push:
          modifier: [sm]
