name: table
label: Table
status: review
context:
  isResponsive: false
  modifier: null
  head:
    row:
      col:
        - cell: Column A
        - cell: Column B
        - cell: Column C
        - cell: Column D
        - cell: Column E
  body:
    row:
      - col:
          - cell: Cell A1
          - cell: Cell B1
          - cell: Cell C1
          - cell: Cell D1
          - cell: Cell E1
      - col:
          - cell: Cell A2
          - cell: Cell B2
          - cell: Cell C2
          - cell: Cell D2
          - cell: Cell E2
      - col:
          - cell: Cell A3
          - cell: Cell B3
          - cell: Cell C3
          - cell: Cell D3
          - cell: Cell E3
      - col:
          - cell: Cell A4
          - cell: Cell B4
          - cell: Cell C4
          - cell: Cell D4
          - cell: Cell E4
      - col:
          - cell: Cell A5
          - cell: Cell B5
          - cell: Cell C5
          - cell: Cell D5
          - cell: Cell E5
variants:
  - name: sm
    label: Small
    context:
      modifier: [sm]
  - name: bordered
    label: Bordered
    context:
      modifier: [bordered]
  - name: align-left
    label: Left-Aligned
    context:
      modifier: [align-left]
  - name: stacked
    label: Stacked
    context:
      modifier: [stacked]
  - name: stacked-horizontal
    label: Stacked, Horizontal
    context:
      modifier: [stacked-horizontal]
  - name: responsive
    label: Responsive
    context:
      isResponsive: true
  - name: muted
    label: Muted
    context:
      body:
        row:
          - col:
              - cell: Cell A1
              - cell: Cell B1
              - cell: Cell C1
              - cell: Cell D1
              - cell: Cell E1
          - col:
              - cell: Cell A2
              - cell: Cell B2
              - cell: Cell C2
              - cell: Cell D2
              - cell: Cell E2
          - col:
              - cell: Cell A3
              - cell: Cell B3
              - cell: Cell C3
              - cell: Cell D3
              - cell: Cell E3
            modifier: [muted]
          - col:
              - cell: Cell A4
              - cell: Cell B4
              - cell: Cell C4
              - cell: Cell D4
              - cell: Cell E4
            modifier: [muted]
          - col:
              - cell: Cell A5
              - cell: Cell B5
              - cell: Cell C5
              - cell: Cell D5
              - cell: Cell E5
            modifier: [muted]
  - name: standout
    label: Standout
    context:
      body:
        row:
          - col:
              - cell: Cell A1
              - cell: Cell B1
              - cell: Cell C1
              - cell: Cell D1
              - cell: Cell E1
          - col:
              - cell: Cell A2
              - cell: Cell B2
              - cell: Cell C2
              - cell: Cell D2
              - cell: Cell E2
            modifier: [standout]
          - col:
              - cell: Cell A3
              - cell: Cell B3
              - cell: Cell C3
              - cell: Cell D3
              - cell: Cell E3
          - col:
              - cell: Cell A4
              - cell: Cell B4
              - cell: Cell C4
              - cell: Cell D4
              - cell: Cell E4
          - col:
              - cell: Cell A5
              - cell: Cell B5
              - cell: Cell C5
              - cell: Cell D5
              - cell: Cell E5
