name: list
label: List
status: wip
context:
  modifier: null
  item:
    - modifier: null
      slot: Item one
    - modifier: null
      slot: Item two
    - modifier: null
      slot: Item three
variants:
  - name: borderless
    label: Borderless
    context:
      modifier: [borderless]
  - name: sm
    label: Small
    context:
      modifier: [sm]
  - name: xs
    label: Extra Small
    context:
      modifier: [xs]
  - name: inset
    context:
      modifier: [inset]
  - name: item-hover
    label: List Item, Hover
    context:
      item:
        - modifier: [hover]
          slot: Item one
        - modifier: [hover]
          slot: Item two
        - modifier: [hover]
          slot: Item three
  - name: item-muted
    label: List Item, Muted
    context:
      item:
        - modifier: null
          slot: Item one
        - modifier: [muted]
          slot: Item two
        - modifier: null
          slot: Item three
  - name: divider
    label: Divider
    context:
      modifier: [borderless]
      item:
        - modifier: null
          slot: Item one
        - modifier: null
          slot: Item two
        - modifier: null
          slot: Item three
          divider: true
        - modifier: null
          slot: Item one
        - modifier: null
          slot: Item two
        - modifier: null
          slot: Item three
