name: list
label: List
status: review
context:
  modifier: null
  isLinks: true
  isSortable: false
  item:
    - modifier: null
      url: '#'
      slot: Item one
    - modifier: null
      url: '#'
      slot: Item two
    - modifier: null
      url: '#'
      slot: Item three
variants:
  - name: non-link
    label: Non-Linked
    context:
      isLinks: false
  - name: borderless
    label: Borderless
    context:
      modifier: [borderless]
  - name: sm
    label: Small
    context:
      modifier: [sm]
  - name: xs
    label: Extra Small
    context:
      modifier: [xs]
  - name: inset
    context:
      modifier: [inset]
  - name: item-hover
    label: List Item, Hover
    context:
      item:
        - modifier: [hover]
          slot: Item one
        - modifier: [hover]
          slot: Item two
        - modifier: [hover]
          slot: Item three
  - name: item-muted
    label: List Item, Muted
    context:
      item:
        - modifier: null
          slot: Item one
        - modifier: [muted]
          slot: Item two
        - modifier: null
          slot: Item three
  - name: item-inset
    label: List Item, Inset
    context:
      item:
        - modifier: [inset]
          icon:
            source: dashboard
          content: Dashboard
        - modifier: [inset]
          icon:
            source: wallet
          content: Accounts
  - name: item-sortable
    label: List Item, Sortable
    context:
      isSortable: true
      item:
        - modifier: [sortable]
          icon:
            source: grip
          content: 1
        - modifier: [sortable]
          icon:
            source: grip
          content: 2
        - modifier: [sortable]
          icon:
            source: grip
          content: 3
  - name: divider
    label: Divider
    context:
      modifier: [borderless]
      item:
        - modifier: null
          slot: Item one
        - modifier: null
          slot: Item two
        - modifier: null
          slot: Item three
          divider: true
        - modifier: null
          slot: Item one
        - modifier: null
          slot: Item two
        - modifier: null
          slot: Item three
