name: content
label: Content
status: wip
context:
  block: true
  push:
    modifier: [lg]
  pull: lg
  heading: false
  thumbnail:
    modifier: [lg]
    utility: [float-left]
variants:
  - name: heading
    label: Heading
    context:
      heading: true
