name: content
label: Content
status: wip
context:
  element:
    push:
      modifier: [lg]
    pull: lg
  thumbnail:
    modifier: [lg]
    utility: [float-left]
variants:
  - name: heading
    label: Heading
    context:
      element:
        heading:
          slot: true
      