name: content
label: Content
status: wip
context:
  contentHeading: null
  contentPush: nullvariants:
  - name: heading
    label: Heading
    context:
      element:
        heading:
          slot: true
      